options(scipen=999)#this option tells RStudio to display numbers in standard rather than scientific notation
library(ftsa) #to get the out-of sample performance metrics, assuming package "ftsa" is already installed

#1.  import data
car.data = read.csv('C:/Users/tmai1/Documents/My RStudio/Rawdata/Car MPG for Predictive Competition Lecture 7.csv')

set.seed(1)



#Conversion from number to factor

car.data$origin=as.factor(car.data$origin)
car.data$model.year=as.factor(car.data$model.year)
#str(ai.patents)

#End of conversion
 #This will make sure that the random data generated by every student is the same

#set.seed(1)
car_index=sample(329,280,replace=F)

car_train=car.data[car_index,]
car_test=car.data[-car_index,]#everything not in the training set should go into testing set
#the minus here means "anything that's not in train dataset yet"

#5. Build model using only training dât
#Build the model using only the training data
Train_model=     lm(mpg~
                   #displacement+
                   #horsepower+
                   weight+
                    model.year+
                     cylinders+
                      origin,
                     
                  # acceleration, 
                   data=car_train)
summary(Train_model)

#6 Build a predictive model
Predicted_test=predict(Train_model,car_test)
error(forecast=Predicted_test, true=car_test$mpg, method="mape")#returns the MAPE of prediction

#7 print the true prices in the testing data next to the predicted prices 
#Summary_of_predictions=data.frame(ai.patents_test$Time,as.data.frame(Predicted_test)[,1])
#View(Summary_of_predictions)

